name: d4rt
description: An interpreter and runtime for the Dart language. It allows you to execute Dart code dynamically in your Dart/Flutter applications
version: 0.3.1
repository: https://github.com/kodjodevf/d4rt
homepage: https://github.com/kodjodevf/d4rt
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.5.0

executables:
  d4rt: interpreter

dependencies:
  analyzer: ^13.3.0
  build: ">=3.0.0 <5.0.0"
  path: ^1.9.1
  source_gen: ">=3.0.0 <5.0.0"

dev_dependencies:
  lints: ^6.1.0
  test: ^1.21.0
  build_runner: ^2.6.0
